const htmlContent = `

<p style="font-size:16px">Hanoi "hash six" streets, Hanoi lemon tea slashing wind, Hanoi ice tea sidewalk ... It seems that these simple descriptions can gather all the most simple things of the capital.&nbsp;Along with the "thousand years of civilization" history, Hanoi always attracts visitors with a distinctive color, a rich cultural identity, and a unique lifestyle that cannot be mixed with anywhere else.&nbsp;If you're curious about the "colors", save the Hanoi travel experience below and schedule a trip to explore the capital.</p>
<p style="font-size:16px">Referring to Hanoi, many people will think about the old features of the old town and historical sites during many feudal dynasties.&nbsp;But never stopping there, Hanoi also has a dynamic rhythm of a growing city day by day.&nbsp;The cultural beauty, combined with the youthful and bustling features, has contributed to creating a colorful Hanoi, able to attract any remote guests.</p>
<div class="mceTemp">&nbsp;</div>
<h2><span  id="1-Thoi-diem-du-lich-Ha-Noi-ly-tuong"><strong>1. The ideal time to travel to Hanoi</strong></span></h2>
<p style="font-size:16px">The climate in Hanoi is also divided into four distinct seasons, each with its own beauty, so you can travel here at any time of the year.&nbsp;However, according to the Hanoi tourism experience, the most famous city is in the flower season and especially in the autumn of Hanoi.</p>
<ul>
<li style="font-size:16px"><strong>Flowering season:</strong>&nbsp;Hanoi is year-round filled with flowering seasons such as peach blossom (January), rash flower (February), skimmed flower (March), lotus flower (summer), milk flower (September - October). , daisies mi mi (October - December) ...</li>
</ul>
<figure id="attachment_19020" class="wp-caption aligncenter" style="width: 300px;"><img class="size-full wp-image-19020" src="https://blog.traveloka.com/source/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3.jpg" sizes="(max-width: 300px) 100vw, 300px" srcset="https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3.jpg 1024w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-150x150.jpg 150w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-300x300.jpg 300w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-768x768.jpg 768w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-640x640.jpg 640w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-585x585.jpg 585w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-220x220.jpg 220w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-3-80x80.jpg 80w" alt="Chinh phục thủ đ&ocirc; với trọn bộ kinh nghiệm du lịch H&agrave; Nội từ A đến Z" width="382" height="300" />
</figure>
<ul>
</br>
<li style="font-size:16px"><strong>Autumn - early winter:</strong>&nbsp;&nbsp;Always going to poetry with so much romance, Hanoi at autumn until early winter is the most beautiful time of the city.&nbsp;The weather was less hot now, the sun was mild, in the chill, there was more scent of milk flowers spread across the streets.</li>
</ul>
<figure id="attachment_19019" class="wp-caption aligncenter" style="width: 1080px;"><img class="size-full wp-image-19019" src="https://blog.traveloka.com/source/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-2.jpg" sizes="(max-width: 1080px) 100vw, 1080px" srcset="https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-2.jpg 819w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-2-240x300.jpg 240w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-2-768x960.jpg 768w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-2-512x640.jpg 512w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-2-585x731.jpg 585w" alt="Chinh phục thủ đ&ocirc; với trọn bộ kinh nghiệm du lịch H&agrave; Nội từ A đến Z" width="382" height="300"" />
&nbsp;</figure>
<h2><span id="2-Den-Ha-Noi-bang-cach-nao"><strong>2. How to get to Hanoi</strong></span></h2>
<p><strong style="font-size:16px">By plane</strong></p>
<p style="font-size:16px">Getting to Hanoi is most convenient by plane.&nbsp;One day, there are many flights&nbsp;<strong>to Hanoi</strong>&nbsp;from all over the city, so you can easily choose the most suitable time frame.</p>
<ul>
<li style="font-size:16px">Flight&nbsp;<strong>Ho Chi Minh City - Hanoi</strong>&nbsp;cost 500,000 - 3,000,000 VND / way, flying in about 2 hours</li>
<li style="font-size:16px">Flight&nbsp;<strong>Danang - Hanoi</strong>&nbsp;costs 300,000 - 1,500,000 VND / way, flight time is about 1 hour 20 minutes</li>
</ul>
<p> <strong style="font-size:16px">Hanoi Travel Combo</strong><span style="font-size:16px" class="goog-text-highlight"> is a new option from Traveloka with a flight and hotel package in one booking. Still comfortable choosing between hundreds of flights and favorite hotels, this Hanoi combo will save you up to 15%, again extremely quickly and easily manage schedules than before.</span>
<p style="font-size:16px">30 km from the center, from Noi Bai airport there are 3 main vehicles to move and the city:</p>
<ul>
<li style="font-size:16px"><em><strong >Taxi: The</strong></em>&nbsp;price ranges from 350,000 to 450,000 VND / trip.&nbsp;You can also catch Grab or Uber for a cheaper price.</li>
<li style="font-size:16px"> <em><strong>Bus:</strong>&nbsp;</em> From the airport, there are 4 buses running into the city.&nbsp;Line 7 (Terminal T1 - Cau Giay), line 17 (Terminal T1 - Long Bien), line 90 (Kim Ma - Terminal T1 - Terminal T2), and Route 86 (Terminal Hanoi - Terminal T1 - Terminal T2).&nbsp;The first three routes have a ticket price of 8,000 - 9,000 VND / time, the 86 route costs 30,000 VND / time.</li>
<li style="font-size:16px"><em><strong>Transit:</strong></em>&nbsp; Domestic airlines have passenger transfers to the center with the price of 40,000 VND / person (not necessarily on the airline's flight).</li>
</ul>
<p><strong style="font-size:16px">By train</strong></p>
<figure id="attachment_19021" class="wp-caption aligncenter" style="width: 1080px;"><img class="size-full wp-image-19021" src="https://blog.traveloka.com/source/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4.jpg" sizes="(max-width: 1080px) 100vw, 1080px" srcset="https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4.jpg 1024w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-150x150.jpg 150w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-300x300.jpg 300w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-768x768.jpg 768w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-640x640.jpg 640w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-585x585.jpg 585w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-220x220.jpg 220w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-4-80x80.jpg 80w" alt="Chinh phục thủ đ&ocirc; với trọn bộ kinh nghiệm du lịch H&agrave; Nội từ A đến Z" width="382" height="300" />
</figure>
<p style="font-size:16px">Hanoi Railway Station is located right in the center, so it will be convenient for those who choose this form to travel to Hanoi.</p>
<p style="font-size:16px">However, if traveling from the southern provinces, it will take you nearly two days for the journey.&nbsp;However, the ticket price is not much different from flying, so according to Hanoi travel experience, this will be an appropriate choice for those who come from the Northern or Central provinces.</p>
<p><strong style="font-size:16px">By bus</strong></p>
<p style="font-size:16px">Coach is also a form of economical transportation for visitors in the neighboring provinces.&nbsp;Hanoi has 4 bus stations, which are My Dinh, Giap Bat, Nuoc Ngam and Gia Lam to cater for the needs of passengers traveling to the capital.</p>
<h2><span  id="3-Phuong-tien-di-chuyen-o-Ha-Noi"><strong>3. Transportation in Hanoi</strong></span></h2>
<figure id="attachment_19039" class="wp-caption aligncenter" style="width: 1080px;"><img class="size-full wp-image-19039" src="https://blog.traveloka.com/source/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-5.jpg" sizes="(max-width: 1080px) 100vw, 1080px" srcset="https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-5.jpg 1024w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-5-300x205.jpg 300w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-5-768x525.jpg 768w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-5-640x437.jpg 640w, https://blog.traveloka.com/vn/wp-content/uploads/sites/9/2018/01/kinh-nghiem-du-lich-ha-noi-tu-a-den-z-5-585x400.jpg 585w" alt="Chinh phục thủ đ&ocirc; với trọn bộ kinh nghiệm du lịch H&agrave; Nội từ A đến Z" width="382" height="300" />
</figure>
<p style="font-size:16px"><em><strong>Motorbike:</strong></em>&nbsp;Renting a motorbike in Hanoi is very simple.&nbsp;You can contact the hotel or call the car rental service directly.&nbsp;The price of a car is about 100,000 - 150,000 VND / day.</p>
<p style="font-size:16px"><em><strong>Taxi:</strong></em>&nbsp;For a comfortable travel, you can choose to travel by taxi.&nbsp;The popular taxi companies in Hanoi are Mai Linh (Phone number: 024.38.222.666), Taxi Group (Phone number: 024.38.26.26.26), V20 (Phone number: 024.38.20.20.20)</p>
<p style="font-size:16px"><em><strong>Cyclo:</strong></em>&nbsp;A typical image of the old town is the cyclo that is still kept for tourism.&nbsp;You can easily catch cyclo while in the old town, stroll around the small streets while listening to interesting stories from cyclo drivers.</p>
<p style="font-size:16px"><em><strong>Tram:</strong></em>&nbsp;Another interesting way to visit the old town is the tram.&nbsp;Tickets are sold at the area of ​​Hoan Kiem Lake for 15,000 VND / 15-minute trip.</p>
<h2>&nbsp;</h2>


`;
export default htmlContent;
